version: "3"

services:
  database_ignite:
    image: postgres
    container_name: database_librarycontrol
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=jonas
      - POSTGRES_PASSWORD=librarycontrol
      - POSTGRES_DB=library_control
    volumes:
      - pgdata:/data/postgres

  librarycontrol:
    build: .
    container_name: node_librarycontrol
    command: npm run dev
    ports:
      - 3001:3001
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
